name: example2

# See: https://docs.lando.dev/config/wordpress.html
recipe: wordpress
config:
  php: '7.4'
  webroot: public
  database: mariadb

# See: https://docs.lando.dev/config/proxy.html
proxy:
  appserver:
    - web.example2.lndo.site
  database:
    - db.example2.lndo.site
  pma:
    - pma.example2.lndo.site
